name: flutter_easy_nfc
description: Nfc library for flutter.
version: 0.0.1
author: JZoom<jzoom8112@gmail.com>
homepage: https://github.com/best-flutter/flutter_easy_nfc

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex: any

flutter:
  plugin:
    androidPackage: org.zoomdev.flutter.nfc
    pluginClass: FlutterEasyNfcPlugin
